"""empty message

Revision ID: cd99327f9775
Revises: 646c1a32c1a1
Create Date: 2024-01-27 14:06:16.140378

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'cd99327f9775'
down_revision = '646c1a32c1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == "production" else None)) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('biography')
        batch_op.drop_column('user_credit')
        batch_op.drop_column('last_name')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == "production" else None)) as batch_op:
        batch_op.add_column(sa.Column('private', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=75), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_credit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('biography', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
