"""empty message

Revision ID: 7f3cd02780d3
Revises: d0cd662e0029
Create Date: 2023-12-01 16:34:28.666201

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '7f3cd02780d3'
down_revision = 'd0cd662e0029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.add_column(sa.Column('launched', sa.Boolean(), server_default='False', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.drop_column('launched')

    # ### end Alembic commands ###
