"""empty message

Revision ID: a4d0e7345570
Revises: b6fae5e3c939
Create Date: 2023-12-05 09:57:39.904067

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'a4d0e7345570'
down_revision = 'b6fae5e3c939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('biography', sa.String(length=1000), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('biography')
        batch_op.drop_column('private')

    # ### end Alembic commands ###
