"""empty message

Revision ID: ae18eee3caca
Revises: 7f3cd02780d3
Create Date: 2023-12-02 16:29:41.741237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae18eee3caca'
down_revision = '7f3cd02780d3'
branch_labels = None
depends_on = None

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
