"""empty message

Revision ID: b6fae5e3c939
Revises: ae18eee3caca
Create Date: 2023-12-02 16:37:35.315047

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'b6fae5e3c939'
down_revision = 'ae18eee3caca'
branch_labels = None
depends_on = None

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(),  server_default=sa.text('NOW()') if environment=="production" else sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=(SCHEMA if environment == 'production' else None)) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
